### PR TITLE
cleaned up the mock data and added more info. Also, cleaned up the ho…

### PR DESCRIPTION
**Pull request by OneTrueAsian**
Please check to see any bugs or changes that are too detrimental, there shouldn't be. Also, i noticed that when you set the min threshold, it crashes... does this work on the app? or does it crash as well?

### CODE REVIEW

**Comment by Littlesnowman88** [comment]
I'm a little confused about the crash you found. I opened the app on your branch and it didn't crash when I set the minimum threshold.
Checking master branch now...

**Comment by Littlesnowman88** [comment]
I found the logic error for setting minimum threshold and maximum capacity and changed it.
Furthermore, once I changed the logic in Event, I added handlers for the minThreshold field and maxCapacity field of AddEvent. You may want to merge my branch into yours. I've tested mine out on my phone and it seems to have worked. The logic isn't permanently set (ex: enforcing some of the fields to be valid), but for now it will work.

**Comment by OneTrueAsian** [comment]
I think that was my issue. I was adding the min and max thresh, but it yelled at me.

**Comment by OneTrueAsian** [comment]
will open new one

**Pull request closed without merging**
