### PR TITLE
Date and Time Validation

### PR DESCRIPTION
**Pull request by OneTrueAsian**
The date and time validation have been added, along with that I also added a Time picker dialog for the user to select time. I also idiot proofed the time selection, and I disabled previous dates, so the user can only select today's date and future times. Allows for Andrew to review for documentation and kelsey for conflictions and errors

### CODE REVIEW

**Comment by Littlesnowman88** [comment]
Hey crew. I just removed myself as a Reviewer because my reviewing has turned into bug fixes, warning cleanups, and some logic fixes. I'll be committing changes soon in response to some of Kelsey's comments.
In response to review right now:
line 141: we are using 24 hour time. Would you prefer we change that? It won't affect database connection.
MockDatabase: for now, I am okay with the empty catch blocks because the mock database will eventually be wiped away with server database calls.
I'm adding some javadoc to event but am not writing all the javadoc for now.

**Comment by OneTrueAsian** [comment]
I'm ok with changing it so it's not 24 hours time, makes it easier to read

**Comment by Littlesnowman88** [comment]
actually, 24hour is making life a lot easier for me, right now. Can I push 24 hour in this update and we modify later?

**Comment by OneTrueAsian** [comment]
> actually, 24hour is making life a lot easier for me, right now. Can I push 24 hours in this update and we modify later?

Sure, but wasn't it originally 24 hours?

**Comment by Littlesnowman88** [comment]
In some ways yes, but in other ways, I think not? I think there was an "hh" where there should have been an "HH".

**Comment by Littlesnowman88** [comment]
My bug fixes have been pushed to this branch. This pull request is open for a brief re-review.

**Pull request merged**
