### PR TITLE
App Settings, Bug Fixes, Documentation

### PR DESCRIPTION
**Pull request by Littlesnowman88**
A Settings Activity has been created with some Android Studio default settings and a much anticipated Dark Mode!!
The Settings Activity can be navigated to from MainActivity.
This pull request includes some overall Documentation upgrades, bug fixes and issue tackling, and cleaner Activity BackStack management (application flow, basically). Activities also fade as they transition now.
Colors have been left alone, but it would be neat to tweak with some colors between light and dark mode.
I failed to fully implement automatic device switching between Day and Night mode, although I'm close. For now, the relevant code has been commented out so the application won't crash.

### CODE REVIEW

**Comment by OneTrueAsian** [comment]
Looked over the settingsActivity, it looks good. There were no inconsistencies that I noticed, some of the auto-generated methods could be deleted because we won't use it.

**Comment by RickRilled** [comment]
LGTM, as said in slack, good eye with the documentation

**Comment by Littlesnowman88** [comment]
Joey and I are trying to get the app to run in the unix lab. We're having some struggles; I'll keep you all updated

**Comment by Littlesnowman88** [comment]
Joey and I succeeded in getting the app to run in android studio!

**Pull request merged**
